name: Deploy Terraform

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
        cli_config_credentials_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        cli_config_credentials_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        cli_config_credentials_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        cli_config_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: terraform apply -auto-approve tfplan
